### PR TITLE
Issue 746

### LINKED ISSUE #746: Different JOIN behaviour after prest upgrade
**Describe the bug**
Performing the same query when joining tables on different versions of prestd (with the same database backend) produces different outputs.

- prestd 1.0.5 -> OK
- prestd 1.0.14 -> NOK

**To Reproduce**
1. Request to endpoint `scans?_join=inner:bodyfat:scans.scancode:$eq:bodyfat.scancode&scans.scancode=$in.000005256e0dc77adbe8f6b25b75eda6748f0818&bodyfat.method=tina`
2. Attached the CSV file of both output as well as the XLS file for comparison. In the XLS I marked the differences with red. As you see we have different results for the same column `scans.gender` and also for the number of returned columns.

**Expected behavior**
Same and correct query results in both cases.

**Desktop (please complete the following information):**
 - pREST version (or commit ref): as written above
 - pREST endpoint: as written above
 - PostgreSQL version: 14.x
 - OS: [e.g. Debian Tid]: Both API running in Kubernetes Popds
 - Go version: NA
 - Log gist: NA

**Additional context**
Database table structure:

```
                                     Table "public.scans"
    Column     |          Type          | Collation | Nullable |           Default            
---------------+------------------------+-----------+----------+------------------------------
 scancode      | character varying(255) |           | not null | 
 creation_date | bigint                 |           | not null | 
 synthetic     | boolean                |           | not null | 
 creator       | character varying(50)  |           | not null | 
 gender        | character varying(50)  |           | not null | 'neutral'::character varying
 clothes       | boolean                |           |          | 
 fists         | boolean                |           |          | 
 pose          | character varying(50)  |           |          | 
 motion        | character varying(50)  |           |          | 
 scene         | character varying(50)  |           |          | 
 raw_data      | character varying(50)  |           |          | 
 user_id       | character varying(100) |           |          | 
 device_id     | character varying(100) |           |          | 
 age           | bigint                 |           |          | 
 weight        | double precision       |           |          | 
 height        | double precision       |           |          | 
 region        | character varying(50)  |           |          | 
 country       | character varying(50)  |           |          | 
 mocap         | boolean                |           | not null | false
 avatar        | character varying(50)  |           |          | 
 campaign      | character varying(255) |           |          | 
 ref_scan      | character varying(255) |           |          | 
 artefacts     | boolean                |           |          | 
 bad_hair      | boolean                |           |          | 
 bad_feet      | boolean                |           |          | 
 verified      | boolean                |           | not null | false
 ref_motion    | character varying(255) |           |          | 
Indexes:
    "scans_pkey" PRIMARY KEY, btree (scancode) 
```

```
                                     Table "public.bodyfat"
     Column      |          Type          | Collation | Nullable |           Default            
-----------------+------------------------+-----------+----------+------------------------------
 bodyfat_id      | integer                |           | not null | generated always as identity
 scancode        | character varying(255) |           | not null | 
 creation_date   | bigint                 |           | not null | 
 percentage      | numeric(7,2)           |           | not null | 
 method          | character varying(50)  |           | not null | 
 device          | character varying(50)  |           |          | 
 meta_cv_release | character varying(50)  |           |          | 
 fitting_id      | integer                |           |          | 
 gender          | character varying(50)  |           |          | 
Indexes:
    "bodyfat_pkey" PRIMARY KEY, btree (bodyfat_id)
    "bf_creation_date_idx" btree (creation_date)
    "bf_meta_cv_release_idx" btree (meta_cv_release)
    "bf_method_idx" btree (method)
    "bf_scancode_idx" btree (scancode)
Foreign-key constraints:
    "fk_fitting_id" FOREIGN KEY (fitting_id) REFERENCES model_fitting_results(fitting_id) ON DELETE CASCADE
    "fk_scancode" FOREIGN KEY (scancode) REFERENCES scans(scancode) ON DELETE CASCADE
```

Cc: @manhofer
[query_result_comparison.xlsx](https://github.com/prest/prest/files/10154654/query_result_comparison.xlsx)
[WORKING_db_query_result.csv](https://github.com/prest/prest/files/10154655/WORKING_db_query_result.csv)
[NOT_WORKING_db_query_result.csv](https://github.com/prest/prest/files/10154656/NOT_WORKING_db_query_result.csv)

### PR DESCRIPTION
**Pull request by arxdsilva**
This is to fix #746, before merging it should include:
- [x] docs
- [x] allow users to setup the JSON agg type with the `prest.toml` file
- [x] allow users to setup the JSON agg type with the `PREST_JSON_AGG_TYPE` env
- [x] tests

Other not related changes:
- [x] replaces the `context.Background()` with cobra's builtin `Context`.

## Summary by CodeRabbit

- **New Features**
  - Introduced flexibility in SQL query aggregation functions through configuration settings.

- **Improvements**
  - Updated command-line tools to use the command's context for migration operations, enhancing the consistency and control over command execution.

- **Refactor**
  - Consolidated configuration loading and parsing functions for improved code maintainability.

- **Tests**
  - Added new test cases to verify the correct assignment of JSON aggregation type in the configuration.

- **Documentation**
  - Updated the version number to reflect new changes in the application.

### CODE REVIEW

**Review by julioshinoda — APPROVED** [review]

File: adapters/postgres/postgres.go [hunk 1]
```diff
@@ -666,7 +666,7 @@ func (adapter *Postgres) QueryCtx(ctx context.Context, SQL string, params ...int
 		log.Errorln(err)
 		return &scanner.PrestScanner{Error: err}
 	}
-	SQL = fmt.Sprintf("SELECT jsonb_agg(s) FROM (%s) s", SQL)
+	SQL = fmt.Sprintf("SELECT %s(s) FROM (%s) s", config.PrestConf.JSONAggType, SQL)
```
Comment (avelino) [inline adapters/postgres/postgres.go:669]: it's important to write tests using sql injection
